version: "3.3"

services:
  database:
    image: mongo
    container_name: mycontainer
    environment:
      MONGO_INITDB_DATABASE: integrado_database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: challenge_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
